### ISSUE TITLE
Create a new tag

### ISSUE THREAD

**Issue by aritomelo** [drupal-composer/preserve-paths#27]
The last version has been for more than a year old and there are 11 commits to be included. 

Please, could you do a new tag release?

**Comment by drupol** [comment]
Hi @derhasi, do you think you can help us on this ? Many thanks!

**Comment by drupol** [comment]
@derhasi Could you please tag a new version ?

**Comment by derhasi** [comment]
I just created a new tag 0.1.5 from current master: https://github.com/drupal-composer/preserve-paths/releases/tag/0.1.5

**Comment by drupol** [comment]
Thanks !!!!!!

**Comment by aritomelo** [comment]
Thanks indeed.
