### ISSUE TITLE
Fix incompatibility with drupal/core-composer-scaffold

### ISSUE THREAD

**Issue by leymannx** [drupal-composer/preserve-paths#30]
Now that drupal-composer/drupal-scaffold mainly got replaced by drupal/core-composer-scaffold preserving paths doesn't work on scaffolding files anymore.

### Steps to reproduce

1. `$ composer create-project drupal-composer/drupal-project:8.x-dev some-dir -n`
2. `$ cd some-dir`
3. `$ composer require drupal-composer/preserve-paths`
4. Add to extra:
    ```
    "preserve-paths": [
          "web/sites/example.settings.local.php"
    ]
    ```
5. `$ echo '$config[\'environment_indicator.indicator\'][\'bg_color\'] = \'#0066ff\';' >> web/sites/example.settings.local.php`
6. `$ composer install -n`

Expected result:
* changes to example.settings.local.php being preserved

Actual result:
* changes to example.settings.local.php overwritten

**Comment by leymannx** [comment]
Can anybody confirm this?

**Comment by leymannx** [comment]
Ah look, this can be overridden by configuring `"drupal-scaffold"` like following.

```json
"drupal-scaffold": {
    "locations": {
        "web-root": "web/"
    },
    "file-mapping": {
        "[web-root]/sites/example.settings.local.php": false
    }
},
```

Should we still go on trying to fix it from this very plugin?

**Comment by tobiasbaehr** [comment]
In D8 you do not need this plugin anymore.
