### ISSUE TITLE
Support of Composer 2 

### ISSUE THREAD

**Issue by mbuechner** [drupal-composer/preserve-paths#35]
I really would appreciate Composer 2 support.

**Comment by VladimirAus** [comment]
@mbuechner pull request are always welcome!
But have a look at #34 and #36

**Comment by webflo** [comment]
Merged in https://github.com/drupal-composer/preserve-paths/pull/36

**Comment by webflo** [comment]
Released as https://github.com/drupal-composer/preserve-paths/releases/tag/0.1.6

**Comment by mbuechner** [comment]
That's fantastic! :bowtie::thumbsup:
